services:

  heasoft:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.heasoft
      args:
        version: "6.33.2"
      network: host
    volumes:
      - ./work:/work
    image: heasoft:v6.33.2
    stdin_open: true
    tty: true

  python:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.python
      network: host
    volumes:
      - ./work:/work
    ports:
      - 8888:8888
    stdin_open: true
    tty: true
