FROM python:3

RUN apt-get update && apt-get install -y \
  curl \
  git \
  vim && \
  rm -rf /var/lib/apt/lists/*

WORKDIR /work

RUN python -m pip install jupyterlab

COPY ./requirements.txt /work
RUN pip install --no-cache-dir -r requirements.txt
